[package]
name = "client"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["dylib"]

[dependencies]
env_logger = "0.11.5"
trident-engine-2024 = { path = "../trident-engine-2024" }
log = "0.4.22"
async-std = "1.13.0"
